/* eslint-disable indent */
export const SEARCH_FILE_START = 'SEARCH_FILE_START';
export const SEARCH_FILE_COMPLETE = 'SEARCH_FILE_COMPLETE';
export const SEARCH_FILE_ERROR = 'SEARCH_FILE_ERROR';

export const SEARCH_REQUEST_START = 'SEARCH_REQUEST_START';
export const SEARCH_REQUEST_COMPLETE = 'SEARCH_REQUEST_COMPLETE';
export const SEARCH_REQUEST_ERROR = 'SEARCH_REQUEST_ERROR';


export const SEARCH_REQUEST_BY_ID_START = 'SEARCH_REQUEST_BY_ID_START';
export const SEARCH_REQUEST_BY_ID_COMPLETE = 'SEARCH_REQUEST_BY_ID_COMPLETE';
export const SEARCH_REQUEST_BY_ID_ERROR = 'SEARCH_REQUEST_BY_ID_ERROR';


export const GET_USER_START = 'GET_USER_START';
export const GET_USER_COMPLETE = 'GET_USER_COMPLETE';
export const GET_USER_ERROR = 'GET_USER_ERROR';
export const GET_USERS_START = 'GET_USERS_START';
export const GET_USERS_COMPLETE = 'GET_USERS_COMPLETE';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';
export const CREATE_USER_START = 'CREATE_USER_START';
export const CREATE_USER_COMPLETE = 'CREATE_USER_COMPLETE';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';

export const APPROVE_EQUIVALENCE_START = 'APPROVE_EQUIVALENCE_START';
export const APPROVE_EQUIVALENCE_COMPLETE = 'APPROVE_EQUIVALENCE_COMPLETE';
export const APPROVE_EQUIVALENCE_ERROR = 'APPROVE_EQUIVALENCE_ERROR';

export const REJECT_EQUIVALENCE_START = 'REJECT_EQUIVALENCE_START';
export const REJECT_EQUIVALENCE_COMPLETE = 'REJECT_EQUIVALENCE_COMPLETE';
export const REJECT_EQUIVALENCE_ERROR = 'REJECT_EQUIVALENCE_ERROR';

export const SEARCH_FILE_BY_FILE_NUMBER_START = 'SEARCH_FILE_BY_FILE_NUMBER_START';
export const SEARCH_FILE_BY_FILE_NUMBER_COMPLETE = 'SEARCH_FILE_BY_FILE_NUMBER_COMPLETE';
export const SEARCH_FILE_BY_FILE_NUMBER_ERROR = 'SEARCH_FILE_BY_FILE_NUMBER_ERROR';

export const CREATE_REQUEST_START = 'CREATE_REQUEST_START';
export const CREATE_REQUEST_COMPLETE = 'CREATE_REQUEST_COMPLETE';
export const CREATE_REQUEST_ERROR = 'CREATE_REQUEST_ERROR';

export const GET_MATCH_START = 'GET_MATCH_START';
export const GET_MATCH_COMPLETE = 'GET_MATCH_COMPLETE';
export const GET_MATCH_ERROR = 'GET_MATCH_ERROR';

export const CONSULT_EQUIVALENCE_START = 'CONSULT_EQUIVALENCE_START';
export const CONSULT_EQUIVALENCE_COMPLETE = 'CONSULT_EQUIVALENCE_COMPLETE';
export const CONSULT_EQUIVALENCE_ERROR = 'CONSULT_EQUIVALENCE_ERROR';

export const DELEGATE_EQUIVALENCE_START = 'DELEGATE_EQUIVALENCE_START';
export const DELEGATE_EQUIVALENCE_COMPLETE = 'DELEGATE_EQUIVALENCE_COMPLETE';
export const DELEGATE_EQUIVALENCE_ERROR = 'DELEGATE_EQUIVALENCE_ERROR';
