export const SEARCH_FILE_START = 'SEARCH_FILE_START';
export const SEARCH_FILE_COMPLETE = 'SEARCH_FILE_COMPLETE';
export const SEARCH_FILE_ERROR = 'SEARCH_FILE_ERROR';

export const SEARCH_REQUEST_START = 'SEARCH_REQUEST_START';
export const SEARCH_REQUEST_COMPLETE = 'SEARCH_REQUEST_COMPLETE';
export const SEARCH_REQUEST_ERROR = 'SEARCH_REQUEST_ERROR';


export const SEARCH_REQUEST_BY_ID_START = 'SEARCH_REQUEST_BY_ID_START';
export const SEARCH_REQUEST_BY_ID_COMPLETE = 'SEARCH_REQUEST_BY_ID_COMPLETE';
export const SEARCH_REQUEST_BY_ID_ERROR = 'SEARCH_REQUEST_BY_ID_ERROR';


export const GET_USER_START = 'GET_USER_START';
export const GET_USER_COMPLETE = 'GET_USER_COMPLETE';
export const GET_USER_ERROR = 'GET_USER_ERROR';
